name: portunus
version: 0.1.0
extras:
  - willing_zg:deployment
  - willing_zg:token_util
  - willing_zg:email
  - willing_zg:chat
  - willing_zg:google_analytics
  - willing_zg:django_willing_zg
  - willing_zg:get_env_util
  - willing_zg:secrets_manager_util
  - willing_zg:secrets_util
  - willing_zg:simple_jwt

exclude:
  - Frontend__Proxy
